#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
OUT="$ROOT/examples/browser_wasm/dist"
PANGO_CAIRO_WASM_DIR="${PANGO_CAIRO_WASM_DIR:-}"

die() {
    echo "error: $*" >&2
    exit 1
}

command -v emcc >/dev/null 2>&1 || die \
    "emcc was not found. Install/activate Emscripten first (source emsdk_env.sh)."

command -v pkg-config >/dev/null 2>&1 || die \
    "pkg-config was not found."

if [[ -z "$PANGO_CAIRO_WASM_DIR" ]]; then
    PANGO_CAIRO_WASM_DIR="$ROOT/.cache/pango-cairo-wasm"
    if [[ ! -d "$PANGO_CAIRO_WASM_DIR/.git" ]]; then
        mkdir -p "$(dirname "$PANGO_CAIRO_WASM_DIR")"
        echo "Cloning VitoVan/pango-cairo-wasm into $PANGO_CAIRO_WASM_DIR..."
        git clone --recurse-submodules \
            https://github.com/VitoVan/pango-cairo-wasm.git \
            "$PANGO_CAIRO_WASM_DIR"
    fi
fi

[[ -d "$PANGO_CAIRO_WASM_DIR/.git" ]] || die \
    "PANGO_CAIRO_WASM_DIR is not a git checkout: $PANGO_CAIRO_WASM_DIR"

cd "$PANGO_CAIRO_WASM_DIR"

# The upstream env.sh expects magicdir to point at the pango-cairo-wasm
# checkout. It was historically provided by the Docker image; provide it
# explicitly for the local build instead.
export magicdir="$PWD"

git submodule update --init --recursive

# VitoVan's build.sh produces env.sh containing the pkg-config paths and
# Emscripten environment needed by the compiled libraries. It is Fedora-based
# upstream, but the actual compilation is performed locally: no Docker.
if [[ ! -f env.sh ]]; then
    echo "Building pango-cairo-wasm locally. This can take 20+ minutes..."
    bash ./build.sh
fi

[[ -f env.sh ]] || die \
    "pango-cairo-wasm build completed without generating env.sh"

# env.sh is an upstream script from an older shell environment and does not
# declare magicdir itself. We provide it above. Temporarily disable nounset
# while sourcing it because some Emscripten setup scripts probe unset vars.
# shellcheck disable=SC1091
set +u
source ./env.sh
set -u

command -v emcc >/dev/null 2>&1 || die \
    "env.sh did not provide a working emcc."

# env.sh supplies the local pkg-config tree generated by pango-cairo-wasm.
# Do not replace it with system libraries: mixing native and wasm packages
# produces invalid link flags.
if ! pkg-config --exists pangocairo; then
    die "pangocairo is not visible through pkg-config after sourcing env.sh"
fi

mkdir -p "$OUT"

PANGOCAIRO_FLAGS="$(
    pkg-config --libs --cflags \
        glib-2.0,gobject-2.0,cairo,pixman-1,freetype2,fontconfig,expat,harfbuzz,pangocairo
)"

# Pango's browser build uses pthreads. This requires a cross-origin-isolated
# page (COOP/COEP). The generated module is therefore intentionally built
# with pthread support rather than pretending Pango is single-threaded.
emcc \
    $PANGOCAIRO_FLAGS \
    "$ROOT/examples/browser_wasm/pango_text.c" \
    -O3 \
    -s MODULARIZE=1 \
    -s EXPORT_ES6=1 \
    -s EXPORT_NAME=createPangoModule \
    -s USE_PTHREADS=1 \
    -s PTHREAD_POOL_SIZE=4 \
    -s ASYNCIFY \
    -s ALLOW_MEMORY_GROWTH=1 \
    -s EXPORTED_FUNCTIONS='["_manim_pango_text_to_svg","_manim_pango_free"]' \
    -s EXPORTED_RUNTIME_METHODS='["ccall","UTF8ToString"]' \
    -o "$OUT/pango_text.js"

cat > "$OUT/pango_text_loader.js" <<'EOF'
import createPangoModule from "./pango_text.js";

let modulePromise;

export async function initializePangoText() {
  if (!modulePromise) {
    modulePromise = createPangoModule({
      locateFile: (file) => new URL(file, import.meta.url).href,
    });
  }

  const Module = await modulePromise;

  window.PangoTextWasm = {
    textToSvg(markup, justify, indent, alignment, width) {
      const ptr = Module.ccall(
        "manim_pango_text_to_svg",
        "number",
        ["string", "number", "number", "number", "number"],
        [markup, justify ? 1 : 0, indent, alignment, width],
      );
      if (!ptr) throw new Error("PangoCairo failed to render text");
      const svg = Module.UTF8ToString(ptr);
      Module.ccall("manim_pango_free", null, ["number"], [ptr]);
      return svg;
    },
  };

  window.manimPangoTextToSvg = window.PangoTextWasm.textToSvg;
  return window.PangoTextWasm;
}

window.manimInitializePangoText = initializePangoText;
EOF

echo "PangoCairo browser WASM built successfully:"
echo "  $OUT/pango_text.js"
echo "  $OUT/pango_text_loader.js"
