from __future__ import annotations

import importlib
import inspect
import json
from dataclasses import dataclass
from types import ModuleType
from typing import Any

import numpy as np

from manimlib.animation.animation import Animation
from manimlib.mobject.mobject import Mobject
from manimlib.mobject.value_tracker import ValueTracker
from manimlib.scene.scene import Scene


DEFAULT_WHITELIST_MODULES = ("manimlib",)

DEFAULT_BLACKLIST = {
    "manimlib": {
        "symbols": {
            "manimlib.os",
            "manimlib.sys",
            "manimlib.Path",
            "manimlib.subprocess",
        },
        "variables": {
            "os",
            "sys",
            "subprocess",
            "Path",
        },
        "methods": {
            "*": {
                "__class__",
                "__dict__",
                "__getattribute__",
                "__setattr__",
                "__delattr__",
                "__subclasses__",
                "__init_subclass__",
            },
            "Scene": {
                "run",
                "tear_down",
                "interact",
                "embed",
                "undo",
                "redo",
                "start_mic_recording",
                "add_sound",
            },
            "Mobject": {
                "set_uniforms",
                "set_data",
                "set_rgba_array",
            },
        },
    }
}


class LLMSceneSafetyError(RuntimeError):
    """Raised when an LLM action violates a security rule."""


class LLMSceneExecutionError(RuntimeError):
    """Raised when an LLM action fails at runtime."""


@dataclass(frozen=True)
class _ModuleBlacklist:
    symbols: set[str]
    variables: set[str]
    methods: dict[str, set[str]]


class LLMSceneController:
    """Safely executes strict JSON plans generated by OpenAI Chat Completions."""

    def __init__(
        self,
        scene: Scene,
        api_key: str,
        base_url: str,
        model: str,
        whitelist_modules: list[str | ModuleType] | None = None,
        blacklist: dict[str, dict[str, Any]] | None = None,
        client: Any | None = None,
        max_request_retries: int = 3,
    ):
        self.scene = scene
        self.model = model
        if client is not None:
            self.client = client
        else:
            try:
                openai_module = importlib.import_module("openai")
            except ModuleNotFoundError as exc:
                raise ImportError(
                    "openai package is required. Install with: pip install \"manimgl[llm]\""
                ) from exc
            self.client = openai_module.OpenAI(api_key=api_key, base_url=base_url)

        requested_modules = whitelist_modules or list(DEFAULT_WHITELIST_MODULES)
        self.whitelist_modules = [
            importlib.import_module(module) if isinstance(module, str) else module
            for module in requested_modules
        ]
        self.allowed_module_names = tuple(module.__name__ for module in self.whitelist_modules)

        self.blacklist = self._normalize_blacklist(blacklist or DEFAULT_BLACKLIST)
        self.allowed_symbols = self._discover_allowed_symbols()
        self.allowed_object_classes = sorted(
            name
            for name, symbol in self.allowed_symbols.items()
            if inspect.isclass(symbol) and issubclass(symbol, Mobject)
        )
        self.allowed_animation_classes = sorted(
            name
            for name, symbol in self.allowed_symbols.items()
            if inspect.isclass(symbol) and issubclass(symbol, Animation)
        )
        self.allowed_methods = self._discover_allowed_methods()
        self.max_request_retries = max(1, int(max_request_retries))

        self.objects: dict[str, Any] = {"scene": self.scene}
        self.updaters: dict[str, tuple[str, Any]] = {}

    def _normalize_blacklist(self, raw: dict[str, dict[str, Any]]) -> dict[str, _ModuleBlacklist]:
        normalized: dict[str, _ModuleBlacklist] = {}
        for module_name, payload in raw.items():
            normalized[module_name] = _ModuleBlacklist(
                symbols=set(payload.get("symbols", set())),
                variables=set(payload.get("variables", set())),
                methods={
                    key: set(values)
                    for key, values in payload.get("methods", {}).items()
                },
            )
        return normalized

    def _discover_allowed_symbols(self) -> dict[str, Any]:
        symbols: dict[str, Any] = {}
        for module in self.whitelist_modules:
            module_blacklist = self.blacklist.get(module.__name__)
            for name in dir(module):
                if name.startswith("_"):
                    continue
                if module_blacklist and name in module_blacklist.variables:
                    continue

                full_name = f"{module.__name__}.{name}"
                if module_blacklist and full_name in module_blacklist.symbols:
                    continue

                symbol = getattr(module, name)
                if inspect.isclass(symbol):
                    symbols[full_name] = symbol
        return symbols

    def _discover_allowed_methods(self) -> list[str]:
        discovered: set[str] = set()
        for symbol in self.allowed_symbols.values():
            if not inspect.isclass(symbol):
                continue
            if not issubclass(symbol, (Scene, Mobject, ValueTracker, Animation)):
                continue
            for name, _ in inspect.getmembers(symbol, predicate=callable):
                if name.startswith("_"):
                    continue
                if self._is_method_blacklisted(symbol, name):
                    continue
                discovered.add(name)
        return sorted(discovered)

    def _is_method_blacklisted(self, cls: type, method_name: str) -> bool:
        module_blacklist = self.blacklist.get(cls.__module__.split(".")[0])
        if not module_blacklist:
            return False

        globally_forbidden = module_blacklist.methods.get("*", set())
        if method_name in globally_forbidden:
            return True

        for base in inspect.getmro(cls):
            forbidden = module_blacklist.methods.get(base.__name__)
            if forbidden and method_name in forbidden:
                return True
        return False

    def _assert_whitelisted_symbol(self, symbol_path: str) -> Any:
        if symbol_path not in self.allowed_symbols:
            raise LLMSceneSafetyError(f"Symbol '{symbol_path}' is not in whitelist")
        return self.allowed_symbols[symbol_path]

    def _assert_allowed_method(self, target: Any, method_name: str) -> None:
        if method_name.startswith("_"):
            raise LLMSceneSafetyError("Private methods are not allowed")
        if method_name not in self.allowed_methods:
            raise LLMSceneSafetyError(f"Method '{method_name}' is not allowed")
        if self._is_method_blacklisted(type(target), method_name):
            raise LLMSceneSafetyError(f"Method '{method_name}' is blacklisted")

    def _build_scene_inventory_message(self) -> str:
        model_ids = sorted(
            key
            for key in self.objects
            if key != "scene"
        )
        max_preview = 40
        preview_lines = []
        for object_id in model_ids[:max_preview]:
            value = self.objects[object_id]
            preview_lines.append(f"- {object_id}: {type(value).__name__}")
        suffix = ""
        if len(model_ids) > max_preview:
            suffix = f"\n- ... (+{len(model_ids) - max_preview} more registered objects)"
        if not preview_lines:
            preview_lines = ["- (none yet)"]
        result = "Available references:\n- scene (Scene)\n" + "\n".join(preview_lines) + suffix
        return result

    def build_json_schema(self) -> dict[str, Any]:
        if not self.allowed_object_classes:
            raise LLMSceneSafetyError("Whitelist produced zero allowed Mobject classes")
        if not self.allowed_animation_classes:
            raise LLMSceneSafetyError("Whitelist produced zero allowed Animation classes")

        value_ref_schema = {
            "type": "object",
            "additionalProperties": False,
            "properties": {
                "kind": {"type": "string", "enum": ["ref"]},
                "id": {"type": "string", "minLength": 1},
            },
            "required": ["kind", "id"],
        }
        vector_schema = {
            "type": "object",
            "additionalProperties": False,
            "properties": {
                "kind": {"type": "string", "enum": ["vector3"]},
                "x": {"type": "number"},
                "y": {"type": "number"},
                "z": {"type": "number"},
            },
            "required": ["kind", "x", "y", "z"],
        }
        tracker_value_schema = {
            "type": "object",
            "additionalProperties": False,
            "properties": {
                "kind": {"type": "string", "enum": ["tracker_value"]},
                "id": {"type": "string", "minLength": 1},
            },
            "required": ["kind", "id"],
        }

        kwargs_entry_schema = {
            "type": "object",
            "additionalProperties": False,
            "properties": {
                "key": {"type": "string", "minLength": 1},
                "value": {"type": ["string", "number", "boolean", "null"]},
            },
            "required": ["key", "value"],
        }

        kwargs_schema = {
            "type": "array",
            "items": kwargs_entry_schema,
        }

        value_schema = {
            "anyOf": [
                {"type": "number"},
                {"type": "string"},
                {"type": "boolean"},
                {"type": "null"},
                {
                    "type": "array",
                    "items": {
                        "anyOf": [
                            {"type": "number"},
                            {"type": "string"},
                            {"type": "boolean"},
                            {"type": "null"},
                        ]
                    },
                },
                value_ref_schema,
                vector_schema,
                tracker_value_schema,
            ]
        }

        operation_schema = {
            "anyOf": [
                {
                    "type": "object",
                    "additionalProperties": False,
                    "properties": {
                        "op": {"type": "string", "enum": ["create_object"]},
                        "id": {"type": "string", "minLength": 1},
                        "class_path": {"type": "string", "enum": self.allowed_object_classes},
                        "args": {"type": "array", "items": value_schema},
                        "kwargs": kwargs_schema,
                        "add_to_scene": {"type": ["boolean", "null"]},
                    },
                    "required": ["op", "id", "class_path", "args", "kwargs", "add_to_scene"],
                },
                {
                    "type": "object",
                    "additionalProperties": False,
                    "properties": {
                        "op": {"type": "string", "enum": ["create_animation"]},
                        "id": {"type": "string", "minLength": 1},
                        "class_path": {"type": "string", "enum": self.allowed_animation_classes},
                        "target": {"type": "string", "minLength": 1},
                        "args": {"type": "array", "items": value_schema},
                        "kwargs": kwargs_schema,
                    },
                    "required": ["op", "id", "class_path", "target", "args", "kwargs"],
                },
                {
                    "type": "object",
                    "additionalProperties": False,
                    "properties": {
                        "op": {"type": "string", "enum": ["call_method"]},
                        "target": {"type": "string", "minLength": 1},
                        "method": {"type": "string", "enum": self.allowed_methods},
                        "args": {"type": "array", "items": value_schema},
                        "kwargs": kwargs_schema,
                        "result_id": {"type": ["string", "null"]},
                        "add_result_to_scene": {"type": ["boolean", "null"]},
                    },
                    "required": ["op", "target", "method", "args", "kwargs", "result_id", "add_result_to_scene"],
                },
                {
                    "type": "object",
                    "additionalProperties": False,
                    "properties": {
                        "op": {"type": "string", "enum": ["add_to_scene"]},
                        "ids": {
                            "type": "array",
                            "items": {"type": "string", "minLength": 1},
                            "minItems": 1,
                        },
                    },
                    "required": ["op", "ids"],
                },
                {
                    "type": "object",
                    "additionalProperties": False,
                    "properties": {
                        "op": {"type": "string", "enum": ["remove_from_scene"]},
                        "ids": {
                            "type": "array",
                            "items": {"type": "string", "minLength": 1},
                            "minItems": 1,
                        },
                    },
                    "required": ["op", "ids"],
                },
                {
                    "type": "object",
                    "additionalProperties": False,
                    "properties": {
                        "op": {"type": "string", "enum": ["play"]},
                        "animation_ids": {
                            "type": "array",
                            "items": {"type": "string", "minLength": 1},
                            "minItems": 1,
                        },
                        "run_time": {"type": ["number", "null"], "minimum": 0},
                        "lag_ratio": {"type": ["number", "null"], "minimum": 0},
                    },
                    "required": ["op", "animation_ids", "run_time", "lag_ratio"],
                },
                {
                    "type": "object",
                    "additionalProperties": False,
                    "properties": {
                        "op": {"type": "string", "enum": ["wait"]},
                        "duration": {"type": ["number", "null"], "minimum": 0},
                    },
                    "required": ["op", "duration"],
                },
                {
                    "type": "object",
                    "additionalProperties": False,
                    "properties": {
                        "op": {"type": "string", "enum": ["add_updater"]},
                        "id": {"type": "string", "minLength": 1},
                        "target": {"type": "string", "minLength": 1},
                        "kind": {
                            "type": "string",
                            "enum": [
                                "increment_value",
                                "follow_tracker",
                                "move_to_path_proportion",
                                "call_method_with_dt",
                            ],
                        },
                        "rate": {"type": ["number", "null"]},
                        "tracker": {"type": ["string", "null"]},
                        "path": {"type": ["string", "null"]},
                        "method": {"type": ["string", "null"]},
                        "scale": {"type": ["number", "null"]},
                        "offset": {"type": ["number", "null"]},
                        "call": {"type": ["boolean", "null"]},
                    },
                    "required": ["op", "id", "target", "kind", "rate", "tracker", "path", "method", "scale", "offset", "call"],
                },
                {
                    "type": "object",
                    "additionalProperties": False,
                    "properties": {
                        "op": {"type": "string", "enum": ["remove_updater"]},
                        "id": {"type": "string", "minLength": 1},
                    },
                    "required": ["op", "id"],
                },
                {
                    "type": "object",
                    "additionalProperties": False,
                    "properties": {
                        "op": {"type": "string", "enum": ["clear_updaters"]},
                        "target": {"type": "string", "minLength": 1},
                        "recurse": {"type": ["boolean", "null"]},
                    },
                    "required": ["op", "target", "recurse"],
                },
            ]
        }

        return {
            "type": "object",
            "additionalProperties": False,
            "properties": {
                "goal": {"type": ["string", "null"]},
                "operations": {
                    "type": "array",
                    "items": operation_schema,
                    "minItems": 1,
                },
            },
            "required": ["goal", "operations"],
        }

    def build_messages(
        self,
        user_prompt: str,
        system_prompt: str | None = None,
    ) -> list[dict[str, str]]:
        default_system = (
            "You are a deterministic planner for Manim scene control via strict JSON schema. "
            "Output JSON only, with no markdown and no extra keys. "
            "Critical ID rules: "
            "(1) You may reference only IDs that already exist in the scene inventory message or IDs you created earlier in this same operations array. "
            "(2) IDs are model-managed. For new objects and animations, choose explicit stable IDs yourself and reuse them consistently. "
            "(3) Before using target, ids, animation_ids, tracker, or path fields, ensure each referenced ID is known. "
            "(4) If a needed object does not exist, first create it with create_object and then use that created ID. "
            "(5) IDs must be fully descriptive and self-explanatory, not generic. "
            "Do not use vague IDs like obj1, item, temp, x, y, a1, mobject_new. "
            "Use explicit semantic IDs such as title_main_text, axis_x_number_line, graph_sine_curve, animation_fade_out_title, tracker_progress_time. "
            "Vector rules: vector3 values must always have x, y, z numeric fields. If there is no 3D content, set z to 0. "
            "Planning rules: prefer minimal valid operations, preserve operation ordering dependencies, and avoid redundant calls. "
            "Schema rules: obey field types exactly, include required fields, and use null explicitly where optional behavior is intended."
        )
        return [
            {"role": "system", "content": system_prompt or default_system},
            {"role": "system", "content": self._build_scene_inventory_message()},
            {"role": "user", "content": user_prompt},
        ]

    def request_plan(
        self,
        user_prompt: str,
        system_prompt: str | None = None,
        temperature: float = 0.0,
        reasoning_effort: str | None = None,
    ) -> dict[str, Any]:
        last_error: Exception | None = None
        for attempt in range(1, self.max_request_retries + 1):
            try:
                request_kwargs = {
                    "model": self.model,
                    "temperature": temperature,
                    "messages": self.build_messages(user_prompt, system_prompt),
                    "response_format": {
                        "type": "json_schema",
                        "json_schema": {
                            "name": "manim_scene_plan",
                            "strict": True,
                            "schema": self.build_json_schema(),
                        },
                    },
                }
                if reasoning_effort is not None:
                    request_kwargs["reasoning_effort"] = reasoning_effort
                response = self.client.chat.completions.create(**request_kwargs)

                content = response.choices[0].message.content
                if not content:
                    raise LLMSceneExecutionError("Model returned an empty response")

                return json.loads(content)
            except Exception as exc:
                last_error = exc
                if attempt >= self.max_request_retries:
                    break

        raise LLMSceneExecutionError(
            f"Request/response failed after {self.max_request_retries} attempts: {last_error}"
        ) from last_error

    def run_prompt(
        self,
        user_prompt: str,
        system_prompt: str | None = None,
        temperature: float = 0.0,
        reasoning_effort: str | None = None,
    ) -> dict[str, Any]:
        plan = self.request_plan(
            user_prompt=user_prompt,
            system_prompt=system_prompt,
            temperature=temperature,
            reasoning_effort=reasoning_effort,
        )
        self.execute_plan(plan)
        return plan

    def execute_plan(self, plan: dict[str, Any]) -> None:
        operations = plan.get("operations", [])
        if not isinstance(operations, list) or not operations:
            raise LLMSceneExecutionError("Plan has no operations")

        for index, op in enumerate(operations):
            if not isinstance(op, dict) or "op" not in op:
                raise LLMSceneExecutionError(f"Operation {index} is invalid")
            try:
                self._execute_operation(op)
            except Exception as exc:
                raise LLMSceneExecutionError(
                    f"Operation {index} ({op.get('op')}) failed: {exc}"
                ) from exc

    def _execute_operation(self, op: dict[str, Any]) -> None:
        opcode = op["op"]
        if opcode == "create_object":
            self._create_object(op)
        elif opcode == "create_animation":
            self._create_animation(op)
        elif opcode == "call_method":
            self._call_method(op)
        elif opcode == "add_to_scene":
            self._add_to_scene(op)
        elif opcode == "remove_from_scene":
            self._remove_from_scene(op)
        elif opcode == "play":
            self._play(op)
        elif opcode == "wait":
            self._wait(op)
        elif opcode == "add_updater":
            self._add_updater(op)
        elif opcode == "remove_updater":
            self._remove_updater(op)
        elif opcode == "clear_updaters":
            self._clear_updaters(op)
        else:
            raise LLMSceneSafetyError(f"Unsupported opcode '{opcode}'")

    def _resolve_value(self, value: Any) -> Any:
        if isinstance(value, dict) and "kind" in value:
            kind = value["kind"]
            if kind == "ref":
                return self._get_object(value["id"])
            if kind == "vector3":
                return np.array([value["x"], value["y"], value["z"]], dtype=float)
            if kind == "tracker_value":
                tracker = self._get_object(value["id"], expected_type=ValueTracker)
                return tracker.get_value()
            raise LLMSceneSafetyError(f"Unknown value kind '{kind}'")
        if isinstance(value, list):
            return [self._resolve_value(item) for item in value]
        return value

    def _resolve_args(self, payload: dict[str, Any]) -> tuple[list[Any], dict[str, Any]]:
        args = [self._resolve_value(item) for item in payload.get("args", [])]
        raw_kwargs = payload.get("kwargs", [])
        kwargs: dict[str, Any] = {}
        if isinstance(raw_kwargs, dict):
            kwargs = {
                key: self._resolve_value(raw)
                for key, raw in raw_kwargs.items()
            }
        elif isinstance(raw_kwargs, list):
            for item in raw_kwargs:
                if not isinstance(item, dict):
                    raise LLMSceneExecutionError("Each kwargs item must be an object")
                key = item.get("key")
                if not isinstance(key, str) or not key:
                    raise LLMSceneExecutionError("Each kwargs item requires a non-empty 'key'")
                kwargs[key] = self._resolve_value(item.get("value"))
        else:
            raise LLMSceneExecutionError("kwargs must be an object or an array")
        return args, kwargs

    def _get_object(self, object_id: str, expected_type: type | None = None) -> Any:
        if object_id not in self.objects:
            raise LLMSceneExecutionError(f"Unknown object id '{object_id}'")
        value = self.objects[object_id]
        if expected_type and not isinstance(value, expected_type):
            raise LLMSceneExecutionError(
                f"Object '{object_id}' is {type(value).__name__}, expected {expected_type.__name__}"
            )
        return value

    def _create_object(self, op: dict[str, Any]) -> None:
        symbol = self._assert_whitelisted_symbol(op["class_path"])
        if not inspect.isclass(symbol) or not issubclass(symbol, Mobject):
            raise LLMSceneSafetyError("create_object only accepts Mobject classes")

        args, kwargs = self._resolve_args(op)
        instance = symbol(*args, **kwargs)
        self.objects[op["id"]] = instance

        if op.get("add_to_scene"):
            self.scene.add(instance)

    def _create_animation(self, op: dict[str, Any]) -> None:
        symbol = self._assert_whitelisted_symbol(op["class_path"])
        if not inspect.isclass(symbol) or not issubclass(symbol, Animation):
            raise LLMSceneSafetyError("create_animation only accepts Animation classes")

        target = self._get_object(op["target"], expected_type=Mobject)
        args, kwargs = self._resolve_args(op)
        animation = symbol(target, *args, **kwargs)
        self.objects[op["id"]] = animation

    def _call_method(self, op: dict[str, Any]) -> None:
        target = self._get_object(op["target"])
        method_name = op["method"]
        self._assert_allowed_method(target, method_name)

        method = getattr(target, method_name, None)
        if method is None or not callable(method):
            raise LLMSceneExecutionError(f"'{method_name}' is not callable on '{op['target']}'")

        args, kwargs = self._resolve_args(op)
        result = method(*args, **kwargs)

        result_id = op.get("result_id")
        if result_id:
            self.objects[result_id] = result

        if op.get("add_result_to_scene") and isinstance(result, Mobject):
            self.scene.add(result)

    def _add_to_scene(self, op: dict[str, Any]) -> None:
        mobjects = [self._get_object(item, expected_type=Mobject) for item in op["ids"]]
        self.scene.add(*mobjects)

    def _remove_from_scene(self, op: dict[str, Any]) -> None:
        mobjects = [self._get_object(item, expected_type=Mobject) for item in op["ids"]]
        self.scene.remove(*mobjects)

    def _play(self, op: dict[str, Any]) -> None:
        animations = [self._get_object(item, expected_type=Animation) for item in op["animation_ids"]]
        kwargs = {}
        if "run_time" in op:
            kwargs["run_time"] = op["run_time"]
        if "lag_ratio" in op:
            kwargs["lag_ratio"] = op["lag_ratio"]
        self.scene.play(*animations, **kwargs)

    def _wait(self, op: dict[str, Any]) -> None:
        duration = op.get("duration")
        if duration is None:
            self.scene.wait()
        else:
            self.scene.wait(duration)

    def _build_updater_callable(self, op: dict[str, Any], target: Mobject):
        kind = op["kind"]

        if kind == "increment_value":
            if not isinstance(target, ValueTracker):
                raise LLMSceneExecutionError("increment_value updater requires a ValueTracker target")
            rate = float(op.get("rate", 1.0))

            def updater(mob: ValueTracker, dt: float = 0.0):
                mob.increment_value(rate * dt)

            return updater

        if kind == "follow_tracker":
            tracker = self._get_object(op["tracker"], expected_type=ValueTracker)
            method_name = op["method"]
            self._assert_allowed_method(target, method_name)
            scale = float(op.get("scale", 1.0))
            offset = float(op.get("offset", 0.0))

            def updater(mob: Mobject, dt: float = 0.0):
                del dt
                method = getattr(mob, method_name)
                method(float(tracker.get_value()) * scale + offset)

            return updater

        if kind == "move_to_path_proportion":
            tracker = self._get_object(op["tracker"], expected_type=ValueTracker)
            path = self._get_object(op["path"], expected_type=Mobject)

            def updater(mob: Mobject, dt: float = 0.0):
                del dt
                mob.move_to(path.point_from_proportion(float(tracker.get_value())))

            return updater

        if kind == "call_method_with_dt":
            method_name = op["method"]
            self._assert_allowed_method(target, method_name)
            scale = float(op.get("scale", 1.0))

            def updater(mob: Mobject, dt: float = 0.0):
                method = getattr(mob, method_name)
                method(scale * dt)

            return updater

        raise LLMSceneSafetyError(f"Unknown updater kind '{kind}'")

    def _add_updater(self, op: dict[str, Any]) -> None:
        updater_id = op["id"]
        if updater_id in self.updaters:
            raise LLMSceneExecutionError(f"Updater '{updater_id}' already exists")

        target = self._get_object(op["target"], expected_type=Mobject)
        updater = self._build_updater_callable(op, target)

        target.add_updater(updater, call=op.get("call", True))
        self.updaters[updater_id] = (op["target"], updater)

    def _remove_updater(self, op: dict[str, Any]) -> None:
        updater_id = op["id"]
        if updater_id not in self.updaters:
            raise LLMSceneExecutionError(f"Updater '{updater_id}' does not exist")

        target_id, updater = self.updaters.pop(updater_id)
        target = self._get_object(target_id, expected_type=Mobject)
        target.remove_updater(updater)

    def _clear_updaters(self, op: dict[str, Any]) -> None:
        target_id = op["target"]
        target = self._get_object(target_id, expected_type=Mobject)
        recurse = bool(op.get("recurse", True))
        target.clear_updaters(recurse=recurse)

        to_delete = [
            updater_id
            for updater_id, (stored_target_id, _) in self.updaters.items()
            if stored_target_id == target_id
        ]
        for updater_id in to_delete:
            del self.updaters[updater_id]
